apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location / {
            return 200 'Hello, World!';
        }

        location /api/ {
          proxy_pass http://example.com/api/;
        }

        error_page  500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
  upstream.conf: |
    upstream example.com {
        server example.com;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest # Using the latest official NGINX image
          env:
            - name: BACKEND_API
              value: "example.com" # You can customize environment variables
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config # Link to the ConfigMap created earlier
