# permissions for end users to view nginxupstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxupstream-viewer-role
rules:
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxupstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxupstreams/status
  verbs:
  - get
