# permissions for end users to edit nginxroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxroutes-editor-role
rules:
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes/status
  verbs:
  - get
