# permissions for end users to view nginxroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxroutes-viewer-role
rules:
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes/status
  verbs:
  - get
