---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes/finalizers
  verbs:
  - update
- apiGroups:
  - nginx.gokul-mylsami.com
  resources:
  - nginxroutes/status
  verbs:
  - get
  - patch
  - update
