apiVersion: nginx.gokul-mylsami.com/v1alpha1
kind: NginxRoutes
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxroutes-sample
spec:
  serverName: "example.com"
  serverBody: |
    location / {
      return 200 'Hello, World!';
    }
  serverPort: 80
  templateFile: "default.conf.template"
