apiVersion: nginx.gokul-mylsami.com/v1alpha1
kind: NginxRoutes
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxroutes-sample
spec:
  # TODO(user): Add fields here
